# Generated by Django 5.0.3 on 2024-03-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
