# Generated by Django 5.0.3 on 2024-03-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_userauth_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
