# Generated by Django 5.0.3 on 2024-03-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_userauth_is_staff_alter_userauth_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='challenge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='credential_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='sign_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userauth',
            name='ukey',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='username',
            field=models.TextField(),
        ),
    ]
