# Generated by Django 5.0.3 on 2024-03-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Food', 'Food'), ('Art & Design', 'Art'), ('Tech', 'Tech'), ('Fashion', 'Fashion'), ('Health & Wellness', 'Health & Wellness')], max_length=50, unique=True),
        ),
    ]
