# Generated by Django 5.0.3 on 2024-03-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_category_description_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('FOOD', 'Food'), ('ART', 'Art'), ('TECH', 'Tech'), ('FASHION', 'Fashion'), ('HEALTH', 'Health & Wellness')], max_length=50, unique=True),
        ),
    ]
