# Generated by Django 5.0.3 on 2024-03-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(choices=[('FOOD', 'Food'), ('ART', 'Art'), ('TECH', 'Tech'), ('FASHION', 'Fashion'), ('HEALTH', 'Health & Wellness')], to='content.category'),
        ),
    ]
