# Generated by Django 5.0.3 on 2024-03-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_content_previous_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='categories',
        ),
    ]
